BEGIN;
--
-- Create model CustomUser
--
CREATE TABLE "users" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "role" varchar(20) NOT NULL, "phone" varchar(20) NOT NULL, "department" varchar(100) NOT NULL, "job_title" varchar(100) NOT NULL, "is_verified" boolean NOT NULL, "last_active" timestamp with time zone NULL, "temp_password" varchar(128) NOT NULL, "force_password_change" boolean NOT NULL, "created_by_id" bigint NULL);
CREATE TABLE "users_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "customuser_id" bigint NOT NULL, "group_id" integer NOT NULL);
--
-- Create model Organization
--
CREATE TABLE "organizations" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(255) NOT NULL UNIQUE, "slug" varchar(100) NOT NULL UNIQUE, "email" varchar(254) NOT NULL, "phone" varchar(20) NOT NULL, "address" text NOT NULL, "is_active" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "admin_user_id" bigint NULL UNIQUE, "created_by_id" bigint NULL);
--
-- Create model Vehicle
--
CREATE TABLE "vehicles" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "vehicle_id" varchar(50) NOT NULL UNIQUE, "make" varchar(100) NOT NULL, "model" varchar(100) NOT NULL, "year" integer NOT NULL, "vin" varchar(17) NOT NULL UNIQUE, "license_plate" varchar(20) NOT NULL, "fuel_type" varchar(20) NOT NULL, "is_active" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "organization_id" bigint NOT NULL);
--
-- Create model UserProfile
--
CREATE TABLE "main_app_userprofile" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date_of_birth" date NULL, "gender" varchar(20) NULL, "alternate_email" varchar(254) NULL, "mobile_phone" varchar(20) NULL, "work_phone" varchar(20) NULL, "emergency_contact" varchar(100) NULL, "emergency_phone" varchar(20) NULL, "address_line1" varchar(255) NULL, "address_line2" varchar(255) NULL, "city" varchar(100) NULL, "state" varchar(100) NULL, "postal_code" varchar(20) NULL, "country" varchar(100) NULL, "employee_id" varchar(50) NULL UNIQUE, "hire_date" date NULL, "job_title" varchar(100) NULL, "department" varchar(100) NULL, "employment_type" varchar(20) NULL, "linkedin_url" varchar(200) NULL, "twitter_handle" varchar(50) NULL, "github_username" varchar(50) NULL, "personal_website" varchar(200) NULL, "profile_picture" varchar(100) NULL, "timezone" varchar(50) NOT NULL, "language" varchar(10) NOT NULL, "theme_preference" varchar(20) NOT NULL, "email_notifications" boolean NOT NULL, "sms_notifications" boolean NOT NULL, "push_notifications" boolean NOT NULL, "two_factor_enabled" boolean NOT NULL, "last_password_change" timestamp with time zone NULL, "account_locked" boolean NOT NULL, "lock_reason" text NULL, "locked_until" timestamp with time zone NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "last_updated_by_id" bigint NULL, "manager_id" bigint NULL, "user_id" bigint NOT NULL UNIQUE);
--
-- Create model ProfileAuditLog
--
CREATE TABLE "main_app_profileauditlog" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action" varchar(20) NOT NULL, "field_changed" varchar(100) NOT NULL, "old_value" text NULL, "new_value" text NULL, "ip_address" inet NULL, "user_agent" text NULL, "timestamp" timestamp with time zone NOT NULL, "changed_by_id" bigint NULL, "profile_id" bigint NOT NULL);
--
-- Create model ParkingRecord
--
CREATE TABLE "parking_records" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "plate_number" varchar(20) NOT NULL, "entry_time" timestamp with time zone NOT NULL, "exit_time" timestamp with time zone NULL, "vehicle_type" varchar(50) NOT NULL, "plate_color" varchar(30) NOT NULL, "vehicle_brand" varchar(50) NOT NULL, "amount_paid" numeric(10, 2) NOT NULL, "payment_time" timestamp with time zone NULL, "payment_method" varchar(30) NOT NULL, "organization" varchar(100) NOT NULL, "parking_duration_minutes" integer NULL, "parking_status" varchar(20) NOT NULL, "created_at" timestamp with time zone NOT NULL);
--
-- Create model Notification
--
CREATE TABLE "main_app_notification" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(255) NOT NULL, "message" text NOT NULL, "notification_type" varchar(20) NOT NULL, "is_read" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "read_at" timestamp with time zone NULL, "action_url" varchar(200) NULL, "action_text" varchar(50) NULL, "user_id" bigint NOT NULL);
--
-- Create model InventoryItem
--
CREATE TABLE "main_app_inventoryitem" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(255) NOT NULL, "item_type" varchar(10) NOT NULL, "description" text NOT NULL, "model" varchar(100) NOT NULL, "year" integer NULL, "color" varchar(50) NOT NULL, "vin" varchar(17) NOT NULL UNIQUE, "vehicle_status" varchar(20) NOT NULL, "part_number" varchar(50) NOT NULL, "category" varchar(100) NOT NULL, "quantity" integer NOT NULL, "min_stock_level" integer NOT NULL, "part_status" varchar(20) NOT NULL, "price" numeric(12, 2) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "created_by_id" bigint NULL);
--
-- Create model FuelTransaction
--
CREATE TABLE "fuel_transactions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "transaction_type" varchar(20) NOT NULL, "liters" numeric(8, 2) NOT NULL, "cost_per_liter" numeric(6, 2) NULL, "total_cost" numeric(10, 2) NULL, "odometer_reading" integer NULL, "location" varchar(255) NULL, "latitude" numeric(10, 8) NULL, "longitude" numeric(11, 8) NULL, "timestamp" timestamp with time zone NOT NULL, "created_at" timestamp with time zone NOT NULL, "driver_id" bigint NULL, "vehicle_id" bigint NOT NULL);
--
-- Create model Document
--
CREATE TABLE "main_app_document" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(255) NOT NULL, "document_type" varchar(50) NOT NULL, "file" varchar(100) NOT NULL, "description" text NULL, "uploaded_at" timestamp with time zone NOT NULL, "is_verified" boolean NOT NULL, "verified_at" timestamp with time zone NULL, "expires_at" date NULL, "uploaded_by_id" bigint NULL, "user_id" bigint NOT NULL, "verified_by_id" bigint NULL);
--
-- Add field organization to customuser
--
ALTER TABLE "users" ADD COLUMN "organization_id" bigint NULL CONSTRAINT "users_organization_id_abe5d649_fk_organizations_id" REFERENCES "organizations"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "users_organization_id_abe5d649_fk_organizations_id" IMMEDIATE;
--
-- Add field user_permissions to customuser
--
CREATE TABLE "users_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "customuser_id" bigint NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model VehicleMovement
--
CREATE TABLE "vehicle_movements" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "trip_id" varchar(100) NOT NULL UNIQUE, "start_location" varchar(255) NOT NULL, "end_location" varchar(255) NOT NULL, "start_latitude" numeric(10, 8) NULL, "start_longitude" numeric(11, 8) NULL, "end_latitude" numeric(10, 8) NULL, "end_longitude" numeric(11, 8) NULL, "start_time" timestamp with time zone NOT NULL, "end_time" timestamp with time zone NULL, "duration_minutes" integer NOT NULL, "distance_km" numeric(10, 2) NOT NULL, "fuel_consumed_liters" numeric(8, 2) NULL, "fuel_cost" numeric(10, 2) NULL, "average_speed_kmh" numeric(5, 2) NULL, "max_speed_kmh" numeric(5, 2) NULL, "trip_status" varchar(20) NOT NULL, "created_at" timestamp with time zone NOT NULL, "driver_id" bigint NULL, "vehicle_id" bigint NOT NULL);
--
-- Create model UserPermission
--
CREATE TABLE "user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "module" varchar(50) NOT NULL, "can_view" boolean NOT NULL, "can_edit" boolean NOT NULL, "can_delete" boolean NOT NULL, "user_id" bigint NOT NULL);
--
-- Create model ActivityLog
--
CREATE TABLE "activity_logs" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action" varchar(20) NOT NULL, "module" varchar(50) NOT NULL, "description" text NOT NULL, "ip_address" inet NULL, "user_agent" text NOT NULL, "timestamp" timestamp with time zone NOT NULL, "organization_id" bigint NULL, "user_id" bigint NOT NULL);
ALTER TABLE "users" ADD CONSTRAINT "users_created_by_id_19a92469_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "users_username_e8658fc8_like" ON "users" ("username" varchar_pattern_ops);
CREATE INDEX "users_created_by_id_19a92469" ON "users" ("created_by_id");
ALTER TABLE "users_groups" ADD CONSTRAINT "users_groups_customuser_id_group_id_927de924_uniq" UNIQUE ("customuser_id", "group_id");
ALTER TABLE "users_groups" ADD CONSTRAINT "users_groups_customuser_id_4bd991a9_fk_users_id" FOREIGN KEY ("customuser_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "users_groups" ADD CONSTRAINT "users_groups_group_id_2f3517aa_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "users_groups_customuser_id_4bd991a9" ON "users_groups" ("customuser_id");
CREATE INDEX "users_groups_group_id_2f3517aa" ON "users_groups" ("group_id");
ALTER TABLE "organizations" ADD CONSTRAINT "organizations_admin_user_id_72567e91_fk_users_id" FOREIGN KEY ("admin_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "organizations" ADD CONSTRAINT "organizations_created_by_id_a135c545_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "organizations_name_eee39956_like" ON "organizations" ("name" varchar_pattern_ops);
CREATE INDEX "organizations_slug_aaafa6fa_like" ON "organizations" ("slug" varchar_pattern_ops);
CREATE INDEX "organizations_created_by_id_a135c545" ON "organizations" ("created_by_id");
ALTER TABLE "vehicles" ADD CONSTRAINT "vehicles_organization_id_f205cb3a_fk_organizations_id" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "vehicles_vehicle_id_1e8e11bb_like" ON "vehicles" ("vehicle_id" varchar_pattern_ops);
CREATE INDEX "vehicles_vin_78b7fb9d_like" ON "vehicles" ("vin" varchar_pattern_ops);
CREATE INDEX "vehicles_organization_id_f205cb3a" ON "vehicles" ("organization_id");
ALTER TABLE "main_app_userprofile" ADD CONSTRAINT "main_app_userprofile_last_updated_by_id_84ed7c71_fk_users_id" FOREIGN KEY ("last_updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "main_app_userprofile" ADD CONSTRAINT "main_app_userprofile_manager_id_bedac55f_fk_main_app_" FOREIGN KEY ("manager_id") REFERENCES "main_app_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "main_app_userprofile" ADD CONSTRAINT "main_app_userprofile_user_id_131f3a5f_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "main_app_userprofile_employee_id_064d7dcc_like" ON "main_app_userprofile" ("employee_id" varchar_pattern_ops);
CREATE INDEX "main_app_userprofile_last_updated_by_id_84ed7c71" ON "main_app_userprofile" ("last_updated_by_id");
CREATE INDEX "main_app_userprofile_manager_id_bedac55f" ON "main_app_userprofile" ("manager_id");
ALTER TABLE "main_app_profileauditlog" ADD CONSTRAINT "main_app_profileauditlog_changed_by_id_bd34e15d_fk_users_id" FOREIGN KEY ("changed_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "main_app_profileauditlog" ADD CONSTRAINT "main_app_profileaudi_profile_id_ce7b6527_fk_main_app_" FOREIGN KEY ("profile_id") REFERENCES "main_app_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "main_app_profileauditlog_changed_by_id_bd34e15d" ON "main_app_profileauditlog" ("changed_by_id");
CREATE INDEX "main_app_profileauditlog_profile_id_ce7b6527" ON "main_app_profileauditlog" ("profile_id");
CREATE INDEX "parking_rec_plate_n_71d6b6_idx" ON "parking_records" ("plate_number", "entry_time");
CREATE INDEX "parking_rec_organiz_214adf_idx" ON "parking_records" ("organization", "entry_time");
ALTER TABLE "main_app_notification" ADD CONSTRAINT "main_app_notification_user_id_af1f7680_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "main_app_notification_user_id_af1f7680" ON "main_app_notification" ("user_id");
ALTER TABLE "main_app_inventoryitem" ADD CONSTRAINT "main_app_inventoryitem_created_by_id_e2dde40a_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "main_app_inventoryitem_vin_5a5dba7e_like" ON "main_app_inventoryitem" ("vin" varchar_pattern_ops);
CREATE INDEX "main_app_inventoryitem_created_by_id_e2dde40a" ON "main_app_inventoryitem" ("created_by_id");
ALTER TABLE "fuel_transactions" ADD CONSTRAINT "fuel_transactions_driver_id_3b3a13c7_fk_users_id" FOREIGN KEY ("driver_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "fuel_transactions" ADD CONSTRAINT "fuel_transactions_vehicle_id_c6e925e2_fk_vehicles_id" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "fuel_transactions_driver_id_3b3a13c7" ON "fuel_transactions" ("driver_id");
CREATE INDEX "fuel_transactions_vehicle_id_c6e925e2" ON "fuel_transactions" ("vehicle_id");
ALTER TABLE "main_app_document" ADD CONSTRAINT "main_app_document_uploaded_by_id_7db5da81_fk_users_id" FOREIGN KEY ("uploaded_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "main_app_document" ADD CONSTRAINT "main_app_document_user_id_5fdac24b_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "main_app_document" ADD CONSTRAINT "main_app_document_verified_by_id_ee8e432b_fk_users_id" FOREIGN KEY ("verified_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "main_app_document_uploaded_by_id_7db5da81" ON "main_app_document" ("uploaded_by_id");
CREATE INDEX "main_app_document_user_id_5fdac24b" ON "main_app_document" ("user_id");
CREATE INDEX "main_app_document_verified_by_id_ee8e432b" ON "main_app_document" ("verified_by_id");
CREATE INDEX "users_organization_id_abe5d649" ON "users" ("organization_id");
ALTER TABLE "users_user_permissions" ADD CONSTRAINT "users_user_permissions_customuser_id_permission_2b4e4e39_uniq" UNIQUE ("customuser_id", "permission_id");
ALTER TABLE "users_user_permissions" ADD CONSTRAINT "users_user_permissions_customuser_id_efdb305c_fk_users_id" FOREIGN KEY ("customuser_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "users_user_permissions" ADD CONSTRAINT "users_user_permissio_permission_id_6d08dcd2_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "users_user_permissions_customuser_id_efdb305c" ON "users_user_permissions" ("customuser_id");
CREATE INDEX "users_user_permissions_permission_id_6d08dcd2" ON "users_user_permissions" ("permission_id");
ALTER TABLE "vehicle_movements" ADD CONSTRAINT "vehicle_movements_driver_id_09c2c5a0_fk_users_id" FOREIGN KEY ("driver_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "vehicle_movements" ADD CONSTRAINT "vehicle_movements_vehicle_id_008ad342_fk_vehicles_id" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "vehicle_movements_trip_id_6de177b5_like" ON "vehicle_movements" ("trip_id" varchar_pattern_ops);
CREATE INDEX "vehicle_movements_driver_id_09c2c5a0" ON "vehicle_movements" ("driver_id");
CREATE INDEX "vehicle_movements_vehicle_id_008ad342" ON "vehicle_movements" ("vehicle_id");
CREATE INDEX "vehicle_mov_vehicle_108c20_idx" ON "vehicle_movements" ("vehicle_id", "start_time");
CREATE INDEX "vehicle_mov_driver__70bc49_idx" ON "vehicle_movements" ("driver_id", "start_time");
CREATE INDEX "vehicle_mov_start_t_884df6_idx" ON "vehicle_movements" ("start_time");
ALTER TABLE "user_permissions" ADD CONSTRAINT "user_permissions_user_id_module_ae4d02a6_uniq" UNIQUE ("user_id", "module");
ALTER TABLE "user_permissions" ADD CONSTRAINT "user_permissions_user_id_b176ff97_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "user_permissions_user_id_b176ff97" ON "user_permissions" ("user_id");
ALTER TABLE "activity_logs" ADD CONSTRAINT "activity_logs_organization_id_f1024604_fk_organizations_id" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "activity_logs" ADD CONSTRAINT "activity_logs_user_id_60cbbbe3_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "activity_logs_organization_id_f1024604" ON "activity_logs" ("organization_id");
CREATE INDEX "activity_logs_user_id_60cbbbe3" ON "activity_logs" ("user_id");
CREATE INDEX "activity_lo_user_id_e40ffe_idx" ON "activity_logs" ("user_id", "timestamp");
CREATE INDEX "activity_lo_organiz_98baa5_idx" ON "activity_logs" ("organization_id", "timestamp");
CREATE INDEX "activity_lo_action_fe3d88_idx" ON "activity_logs" ("action", "timestamp");
COMMIT;
