# Generated by Django 4.2.15 on 2025-12-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_location_to_organization'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='parkingrecord',
            index=models.Index(fields=['is_weekend', 'entry_time'], name='parking_rec_is_week_9cc412_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingrecord',
            index=models.Index(fields=['is_peak_hours', 'entry_time'], name='parking_rec_is_peak_f7a66a_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingrecord',
            index=models.Index(fields=['vehicle_usage_type'], name='parking_rec_vehicle_172534_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingrecord',
            index=models.Index(fields=['duration_category'], name='parking_rec_duratio_b2cc46_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingrecord',
            index=models.Index(fields=['revenue_category'], name='parking_rec_revenue_da9ae1_idx'),
        ),
    ]
