# Generated by Django 5.2.9 on 2025-12-19 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_inventoryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=50, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('license_plate', models.CharField(max_length=20)),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='main_app.organization')),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['vehicle_id'],
            },
        ),
        migrations.CreateModel(
            name='FuelTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Fuel Purchase'), ('consumption', 'Fuel Consumption')], max_length=20)),
                ('liters', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost_per_liter', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('odometer_reading', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_transactions', to='main_app.vehicle')),
            ],
            options={
                'db_table': 'fuel_transactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VehicleMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=100, unique=True)),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('start_latitude', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('start_longitude', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
                ('end_latitude', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('end_longitude', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_consumed_liters', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('fuel_cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('average_speed_kmh', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('max_speed_kmh', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('trip_status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_trips', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='main_app.vehicle')),
            ],
            options={
                'db_table': 'vehicle_movements',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['vehicle', 'start_time'], name='vehicle_mov_vehicle_108c20_idx'), models.Index(fields=['driver', 'start_time'], name='vehicle_mov_driver__70bc49_idx'), models.Index(fields=['start_time'], name='vehicle_mov_start_t_884df6_idx')],
            },
        ),
    ]
