# Generated by Django 4.2.15 on 2025-12-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_parkingrecord_parking_rec_is_week_9cc412_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='parkingrecord',
            new_name='combined_da_plate_n_ece7a2_idx',
            old_name='parking_rec_plate_n_71d6b6_idx',
        ),
        migrations.RenameIndex(
            model_name='parkingrecord',
            new_name='combined_da_organiz_8b7af1_idx',
            old_name='parking_rec_organiz_214adf_idx',
        ),
        migrations.RenameIndex(
            model_name='parkingrecord',
            new_name='combined_da_is_week_1b7af0_idx',
            old_name='parking_rec_is_week_9cc412_idx',
        ),
        migrations.RenameIndex(
            model_name='parkingrecord',
            new_name='combined_da_is_peak_206c56_idx',
            old_name='parking_rec_is_peak_f7a66a_idx',
        ),
        migrations.RenameIndex(
            model_name='parkingrecord',
            new_name='combined_da_vehicle_0b643b_idx',
            old_name='parking_rec_vehicle_172534_idx',
        ),
        migrations.RenameIndex(
            model_name='parkingrecord',
            new_name='combined_da_duratio_1871ae_idx',
            old_name='parking_rec_duratio_b2cc46_idx',
        ),
        migrations.RenameIndex(
            model_name='parkingrecord',
            new_name='combined_da_revenue_583080_idx',
            old_name='parking_rec_revenue_da9ae1_idx',
        ),
        migrations.AlterModelTable(
            name='parkingrecord',
            table='combined_dataset',
        ),
    ]
