# Generated by Django 4.2.15 on 2025-12-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_vehicle_fueltransaction_vehiclemovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemovement',
            name='duration_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='trip_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('active', 'Active'), ('in_progress', 'In Progress'), ('cancelled', 'Cancelled')], default='completed', max_length=20),
        ),
    ]
