# Generated by Django 5.2.9 on 2025-12-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_vehiclemovement_duration_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('plate_color', models.CharField(max_length=30)),
                ('vehicle_brand', models.CharField(max_length=50)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_time', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(max_length=30)),
                ('organization', models.CharField(max_length=100)),
                ('parking_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('parking_status', models.CharField(default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'parking_records',
                'ordering': ['-entry_time'],
                'indexes': [models.Index(fields=['plate_number', 'entry_time'], name='parking_rec_plate_n_71d6b6_idx'), models.Index(fields=['organization', 'entry_time'], name='parking_rec_organiz_214adf_idx')],
            },
        ),
    ]
