# Generated by Django 4.2.15 on 2025-12-22 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_parkingrecord'),
    ]

    operations = [
    ]
